### ISSUE TITLE
Add support for loops and iterations of commands

### ISSUE THREAD

**Issue by whotwagner** [ait-testbed/attackmate#107]
Currently loops are limited to execute the same command until a specific result is returned. It would be nice to run blocks of commands in loops until a specific condition is met

**Comment by thorinaboenke** [comment]
as a workaround in the meantime, would it be possible to use include commands for that?

**Comment by whotwagner** [comment]
only partly. we need to design that feature first, due to the complexity

**Comment by thorinaboenke** [comment]
implmented in https://github.com/ait-testbed/attackmate/pull/125
