### ISSUE TITLE
Add json-command

### ISSUE THREAD

**Issue by whotwagner** [ait-testbed/attackmate#121]
Currently attackm8 is not able to parse json-data. It would be very useful to have a json-command that can parse json-data and store defined values in variables

**Comment by thorinaboenke** [comment]
1) parse from file
2) take output from previous command (if valid json)

**Comment by whotwagner** [comment]
if there the "local_path" option is used, read the json from this command. cmd is optional. if local_path is defined, cmd will be ignored. if no local_path is set, read the json from "cmd"

We also need to support, reading every possible json format. even if our varstore is currently limited to strings and list[str] for now. I would suggest to flatten the json to have the full path to the value as a string(like: person[0]_address_street aso..)
