### ISSUE TITLE
Remove validate_prompt for ssh-commands

### ISSUE THREAD

**Issue by whotwagner** [ait-testbed/attackmate#24]
validate_prompts is not necessary and should be removed. None could be used for "don't validate prompt"

**Comment by thorinaboenke** [comment]
@whotwagner does that only mean that the default should be changed to false (i.e. not to validate prompts) or the entire functionality removed? I found it pretty helpful for debugging the network scenario actually

**Comment by whotwagner** [comment]
No, I thought that an extra variable is not necessary. We could validate if the list of prompts is None. If it is None -> don't validate_prompts
