### ISSUE TITLE
Debug-Executor should write variable-value into output.log

### ISSUE THREAD

**Issue by whotwagner** [ait-testbed/attackmate#61]
Debug-Executor should write variable-value into output.log. Currently it writes the command into the log

**Comment by thorinaboenke** [comment]
Am I'm not sure I understood this right; for a debug command such as

currently the output.log line for a Debug Command looks like this:
```                         
--- 2024-06-18 15:36:14 INFO: ---

Command: This is the Metasploit Variable: 192.168.10.35
```

and the desired output would be this?
```
Command: This is the Metasploit Variable: $METASPLOIT
This is the Metasploit Variable: 192.168.10.35
```

**Comment by whotwagner** [comment]
oh, maybe this issue has already been fixed but not closed. The output in the first example is fine.

**Comment by thorinaboenke** [comment]
Then we're good i think :)
